package io.openems.edge.evcharger.managed.base;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evcharger.api.data.OperationMode;
import io.openems.edge.evcharger.api.data.Priority;

@ObjectClassDefinition(//
		name = "EvCharger Managed", //
		description = "Managed EvCharger.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evChargerMgt0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "EvCharger-ID", description = "ID of EvCharger device.", required = true)
	String evcharger_id() default "evCharger0";

	@AttributeDefinition(name = "OperationMode", description = "EvCharger Operation mode.")
	OperationMode operationMode() default OperationMode.Automatic;

	@AttributeDefinition(name = "Priority", description = "Priority of the EvCharger.")
	Priority priority() default Priority.LOW;

	@AttributeDefinition(name = "Energy limit", description = "Set the Energylimit for this or the next Session in [Wh]. '0' is no limit.")
	int energySessionLimit() default 0;

	@AttributeDefinition(name = "EvCharger target filter", description = "This is auto-generated by 'EvCharger-ID'.")
	String evcharger_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EvCharger Managed [{id}]";

}