package io.openems.edge.evcs.abl;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evcs.api.Evcs;
import io.openems.edge.evcs.api.PhaseRotation;
import io.openems.edge.evcs.api.Priority;

@ObjectClassDefinition(//
		name = "EVCS Abl", //
		description = "Implementation for the Abl em4 charging station")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evcs0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Plug", description = "The Plug that is used.")
	Plug plug() default Plug.PLUG_1;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Minimum hardware current", description = "Minimum charging power of the Charger in W.", required = true)
	int minHwCurrent() default Evcs.DEFAULT_MINIMUM_HARDWARE_CURRENT;

	@AttributeDefinition(name = "Maximum hardware current", description = "Maximum charging power of the Charger in W.", required = true)
	int maxHwCurrent() default Evcs.DEFAULT_MAXIMUM_HARDWARE_CURRENT;

	@AttributeDefinition(name = "Phase rotation", description = "The way in which the phases are physically swapped")
	PhaseRotation phaseRotation() default PhaseRotation.L1_L2_L3;

	@AttributeDefinition(name = "Charge Priority", description = "Priority in comparison to other chargepoints.")
	Priority priority() default Priority.LOW;

	@AttributeDefinition(name = "Debug Mode", description = "Activates the debug mode")
	boolean debugMode() default false;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EVCS Abl [{id}]";

}