package io.openems.edge.controller.hackathon;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Hackathon Heating", //
		description = "This Controller enables a Relay, depending on the input Temperature")
@interface Config {
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlHackathonHeating0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Thermometer Id", description = "Id of the Thermometer, providing the Temperature input for the Controller.")
	String thermometer_id() default "temp0";

	@AttributeDefinition(name = "Activation Temperature", description = "When to enable the relay.")
	int enable_temperature() default 300;

	@AttributeDefinition(name = "Deativation Temperature", description = "When to disable the relay.")
	int disable_temperature() default 700;

	@AttributeDefinition(name = "Relay Id", description = "Id of the Relay, you control.")
	String relay_id() default "rel0";

	@AttributeDefinition(name = "Thermometer target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String thermometer_target() default "(enabled=true)";

	@AttributeDefinition(name = "Thermometer target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String relay_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Hackathon Heating [{id}]";
}