package io.openems.edge.consolinno.meter.mbus;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Meter MBus Heat", //
		description = "A HeatMeter Communicating via MBus." //
)
@interface ConfigHeatMeter {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "heatmeter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "HeatMeter";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Model", description = "Identification via model")
	HeatMeterModel model() default HeatMeterModel.ELSTER_SENSOSTAR_2;

	@AttributeDefinition(name = "MBus-Bridge Id", description = "The Unique Id of the mBus-Bridge you what to allocate to this device.")
	String Mbus_Id() default "mbus0";

	@AttributeDefinition(name = "PrimaryAddress", description = "primary Address of the Mbus Component")
	int primaryAddress() default 1;

	@AttributeDefinition(name = "Polling Interval", description = "This is the wait time between polling. Unit is seconds.")
	int pollingIntervalSeconds() default 0;

	@AttributeDefinition(name = "MBus target filter", description = "This is auto-generated by 'Mbus-ID'.")
	String Mbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Heat-meter Device Id [{id}]";

}
