package io.openems.edge.consolinno.meter.mbus;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Meter MBus Water", //
		description = "Implements a water meter communicating via M-Bus." //
)
@interface ConfigWaterMeter {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "watermeter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "WaterMeter";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "M-Bus bridge ID", description = "ID of the M-Bus bridge this device should use.")
	String wmbus_Id() default "mbus0";

	@AttributeDefinition(name = "M-Bus PrimaryAddress", description = "PrimaryAddress of the M-Bus device.")
	int primaryAddress() default 1;

	@AttributeDefinition(name = "Model", description = "Choose the meter model. This selects at which record positions to "
			+ "look for the data in the transmission. \"Autosearch record position\" should work for most models.")
	WaterMeterModelMbus model() default WaterMeterModelMbus.AUTOSEARCH;

	@AttributeDefinition(name = "Polling Interval", description = "This is the wait time between polling. Unit is seconds.")
	int pollingIntervalSeconds() default 0;

	@AttributeDefinition(name = "MBus target filter", description = "This is auto-generated by 'Mbus-ID'.")
	String Mbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Water meter M-Bus [{id}]";

}
