package io.openems.edge.controller.evcharger.fixactivepower;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evcharger.api.data.OperationMode;

@ObjectClassDefinition(//
		name = "Controller EvCharger Fix Active Power", //
		description = "Fix active power controller for an EvCharger.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlEvChargerFix0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "ManagedEvCharger-ID", description = "ID of the ManagedEvCharger component.", required = true)
	String managedEvCharger_id() default "evChargerMgt0";

	@AttributeDefinition(name = "OperationMode", description = "Operation mnode of the evcharger.")
	OperationMode operationMode() default OperationMode.Automatic;

	@AttributeDefinition(name = "ActivePower per Phase", description = "Set the active power per Phase in [W].")
	int activePowerPerPhase() default 11080;

	@AttributeDefinition(name = "Max Phases", description = "Sets the number of max phases to use [1,2,3] (only if supported by chargepoint hardware).")
	int maxUsablePhases() default 3;

	@AttributeDefinition(name = "Energy limit", description = "Set the Energylimit for this or the next Session in [Wh]. '0' is no limit.")
	int energySessionLimit() default 0;

	@AttributeDefinition(name = "ManagedEvCharger target filter", description = "This is auto-generated by 'ManagedEvCharger-ID'.")
	String managedEvCharger_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller EvCharger Fix Active Power [{id}]";

}