package io.openems.edge.consolinno.meter.mbus.wmbus;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(
        name = "Meter Water Wireless MBus",
        description = "Implements a water meter communicating via Wireless M-Bus.")
@interface ConfigWaterMeterWirelessMbus {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
    String id() default "watermeter0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
    String alias() default "WaterMeter";

    @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "WmBus-Bridge Id", description = "The Unique Id of the mBus-Bridge you what to allocate to this device.")
    String Wmbus_Id() default "wmbus0";

    @AttributeDefinition(name = "Wireless M-Bus radio address", description = "Radio address of the WM-Bus device. Needed Length: 8")
    String radioAddress() default "";

    @AttributeDefinition(name = "Model", description = "Choose the meter model. This selects at which record positions to "
            + "look for the data in the transmission. \"Autosearch record position\" should work for most models.")
    WaterMeterModelWirelessMbus model() default WaterMeterModelWirelessMbus.AUTOSEARCH;
    @AttributeDefinition(name = "Decryption key", description = "Decryption key of the WM-Bus telegram. Leave empty if not encrypted.", type = AttributeType.PASSWORD)
    String key() default "";

    @AttributeDefinition(name = "MBus target filter", description = "This is auto-generated by 'Wmbus-ID'.")
    String Wmbus_target() default "(enabled=true)";


    String webconsole_configurationFactory_nameHint() default "Water meter Wireless M-Bus [{id}]";

}
