package io.openems.edge.consolinno.meter.mbus.generic;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Meter Gas MBus Generic", //
		description = "A GasMeter Communicating via MBus." //
)
@interface ConfigGasMeter {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "gasmeter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "GasMeter";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "MBus-Bridge Id", description = "The Unique Id of the mBus-Bridge you what to allocate to this device.")
	String Mbus_id() default "mbus0";

	@AttributeDefinition(name = "PrimaryAddress", description = "primary Address of the Mbus Component.")
	int primaryAddress() default 1;

	@AttributeDefinition(name = "Meter reading", description = "The address for meter reading of this meter.")
	int meterReading() default -404;

	@AttributeDefinition(name = "Meter reading energy", description = "The address for meter reading energy of this meter.")
	int totalConsumedEnergyAddress() default -404;

	@AttributeDefinition(name = "Flow temp", description = "The address for flow temp of this meter.")
	int flowTempAddress() default -404;

	@AttributeDefinition(name = "Return temp", description = "The address for return temp of this meter.")
	int returnTempAddress() default -404;

	@AttributeDefinition(name = "Flow rate", description = "The address for flow rate of this meter.")
	int flowRateAddress() default -404;

	@AttributeDefinition(name = "Polling Interval", description = "This is the wait time between polling. Unit is seconds.")
	int pollingIntervalSeconds() default 0;

	@AttributeDefinition(name = "MBus target filter", description = "This is auto-generated by 'Mbus-ID'.")
	String Mbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Gas-meter Device Id [{id}]";

}
